services:
  - type: web
    name: odoo-app
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
    disk:
      name: odoo-data
      mountPath: /var/lib/odoo
      sizeGB: 1